manifest:
  remotes:
    - name: marzelwidmer
      url-base: https://github.com/marzelwidmer

  projects:
    - name: zmk
      remote: marzelwidmer
      revision: animated-widgets
#      revision: niceview
#      revision: dancer
      import: app/west.yml
  self:
    path: config
